name: Sonatype Lifecycle Evaluation

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SonatypeUrl: 'https://finos.sonatype.app/platform/'
      SonatypeAppId: 'morphir-elm'
      SonatypeStage: 'build'
      SonatypeScanTarget: "redistributable/SpringBoot/pom.xml package-lock.json"
      ExcludeDirectory: " -D dirExcludes='**/website/, **/docs/, **/.*'"
      
    steps:
    - uses: actions/checkout@v1

    - name: Sonatype Lifecycle Software Composition Analysis (SCA) Scan
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        username: ${{ secrets.sonatype_user }}
        password: ${{ secrets.sonatype_password }}
        serverUrl: ${{ env.SonatypeUrl }}
        applicationId: ${{ env.SonatypeAppId }}
        stage: 'stage-release'
        target: '.'
    
    - name: Sonatype Lifecycle Software Composition Analysis (SCA) Scan
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        username: ${{ secrets.sonatype_user }}
        password: ${{ secrets.sonatype_password }}
        serverUrl: ${{ env.SonatypeUrl }}
        applicationId: ${{ env.SonatypeAppId }}
        stage: ${{ env.SonatypeStage }}
        target: ${{ env.SonatypeScanTarget }} ${{ env.ExcludeDirectory }}
